language: java
install: true

jdk:
  - oraclejdk8

branches:
  only:
  - master


before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

addons:
  sonarcloud:
    organization: "dmitriyoparin-github"
    token:
      secure: $SONARCLOUD_TOKEN

script:
  - sonar-scanner
  -
# разворачивание на heroku
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: sitecalculatingareafigures

# отправка сообщений о неуспешной сборки проекта
notifications:
  email:
    recipients:
      - www.odo6@yandex.ru
    on_success: never
    on_failure: never #always


