language: java
install: true

jdk:
  - oraclejdk8
branches:
  only:
    - master

script:
  - ./gradlew assemble
  - ./gradlew check


# разворачивание на heroku
deploy:
  provider: heroku
  api_key:
    secure: 6c856219-4974-4feb-b4c3-41dfd72aad1e
  app: sitecalculatingareafigures

# отправка сообщений о неуспешной сборки проекта
notifications:
  email:
    recipients:
      - www.odo6@yandex.ru
    on_success: never
    on_failure: always