language: java

jdk:
  - oraclejdk8


before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar


# разворачивание на heroku
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: myproga

# отправка сообщений о неуспешной сборки проекта
notifications:
  email:
    recipients:
      - www.odo6@yandex.ru
    on_success: never
    on_failure: never #always