language: java
install: true

jdk:
  - oraclejdk8

# разворачивание на heroku
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: sitecalculatingareafigures

# отправка сообщений о неуспешной сборки проекта
notifications:
  email:
    recipients:
      - www.odo6@yandex.ru
    on_success: never
    on_failure: always